version: '2.4'
services:
  # db:
  #   build:
  #     context: .
  #     dockerfile: win-mysql.dockerfile
  #   image: mysql:v1.0
  #   environment:
  #   - MYSQL_ROOT_PASSWORD=simple
  #   user: Administrator
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - main
  db-client:
    # build:
    #   context: .
    #   dockerfile: win-mysql-client.dockerfile
    image: mysql_client:v1.0
    user: Administrator
    # depends_on:
    #   - db
    # command: mysql -u root -psimple -h db -e 'SELECT User, Host FROM mysql.user'
    command: ["mysql -u root -psimple -h db -e 'SELECT User, Host FROM mysql.user'"]
    # networks:
    #   - main
networks:
  default:
    external:
      name: datajoint-windows_main
